export const data = [
  {
    id: 1,
    name: "Anirudh",
    class: 8,
    sub1: "Physics",
    sub2: "Maths",
    sub3: "History",
  },
  {
    id: 2,
    name: "Malik",
    class: 7,
    sub1: "Chemistry",
    sub2: "English",
    sub3: "Geography",
  },
  {
    id: 3,
    name: "Reena",
    class: 12,
    sub1: "Drawing",
    sub2: "Arts",
    sub3: "Hindi",
  },
  {
    id: 4,
    name: "Yamini",
    class: 6,
    sub1: "Biology",
    sub2: "General Knowledge",
    sub3: "Computer",
  },
  {
    id: 5,
    name: "Atul",
    class: 11,
    sub1: "Physical Education",
    sub2: "Tally",
    sub3: "Networking",
  },
];
